development:
  adapter: postgresql
  encoding: unicode
  database: network_development
  pool: 5
  host: db 
  username: postgres
  password: qwerty123
  

test:
  adapter: postgresql
  encoding: unicode
  database: network_test
  pool: 5
  host: db
  timeout: 5000
  username: eclipse
  password: qwerty123
  port: 5432
