development:
  adapter: postgresql
  encoding: unicode
  database: network_development
  pool: 5
  timeout: 5000
  username: eclipse
  password: qwerty123
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: network_test
  pool: 5
  timeout: 5000
  username: eclipse
  password: qwerty123
  port: 5432
