development:
  adapter: postgresql
  encoding: unicode
  database: network_development
  pool: 5
  host: db 
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  

test:
  adapter: postgresql
  encoding: unicode
  database: network_test
  pool: 5
  host: db
  timeout: 5000
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5432
